/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XaiRouteImport } from './routes/xai'
import { Route as WaveletsRouteImport } from './routes/wavelets'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UploadTrainRouteImport } from './routes/upload-train'
import { Route as ThresholdsRouteImport } from './routes/thresholds'
import { Route as ThresholdEvolutionRouteImport } from './routes/threshold-evolution'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as StreamControlRouteImport } from './routes/stream-control'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SpectralRouteImport } from './routes/spectral'
import { Route as ResearchExportRouteImport } from './routes/research-export'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as PredictiveFailureRouteImport } from './routes/predictive-failure'
import { Route as PhysicsRouteImport } from './routes/physics'
import { Route as ModelValidationRouteImport } from './routes/model-validation'
import { Route as ModelProfilesRouteImport } from './routes/model-profiles'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LatentRouteImport } from './routes/latent'
import { Route as FusionRouteImport } from './routes/fusion'
import { Route as FftRouteImport } from './routes/fft'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as DefectEvolutionRouteImport } from './routes/defect-evolution'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemWebsocketRouteImport } from './routes/system.websocket'
import { Route as SystemRuntimeRouteImport } from './routes/system.runtime'
import { Route as SystemEdgeRouteImport } from './routes/system.edge'
import { Route as SystemApiHealthRouteImport } from './routes/system.api-health'

const XaiRoute = XaiRouteImport.update({
  id: '/xai',
  path: '/xai',
  getParentRoute: () => rootRouteImport,
} as any)
const WaveletsRoute = WaveletsRouteImport.update({
  id: '/wavelets',
  path: '/wavelets',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTrainRoute = UploadTrainRouteImport.update({
  id: '/upload-train',
  path: '/upload-train',
  getParentRoute: () => rootRouteImport,
} as any)
const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const ThresholdEvolutionRoute = ThresholdEvolutionRouteImport.update({
  id: '/threshold-evolution',
  path: '/threshold-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamControlRoute = StreamControlRouteImport.update({
  id: '/stream-control',
  path: '/stream-control',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectralRoute = SpectralRouteImport.update({
  id: '/spectral',
  path: '/spectral',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchExportRoute = ResearchExportRouteImport.update({
  id: '/research-export',
  path: '/research-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveFailureRoute = PredictiveFailureRouteImport.update({
  id: '/predictive-failure',
  path: '/predictive-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsRoute = PhysicsRouteImport.update({
  id: '/physics',
  path: '/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelValidationRoute = ModelValidationRouteImport.update({
  id: '/model-validation',
  path: '/model-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelProfilesRoute = ModelProfilesRouteImport.update({
  id: '/model-profiles',
  path: '/model-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LatentRoute = LatentRouteImport.update({
  id: '/latent',
  path: '/latent',
  getParentRoute: () => rootRouteImport,
} as any)
const FusionRoute = FusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const FftRoute = FftRouteImport.update({
  id: '/fft',
  path: '/fft',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectEvolutionRoute = DefectEvolutionRouteImport.update({
  id: '/defect-evolution',
  path: '/defect-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemWebsocketRoute = SystemWebsocketRouteImport.update({
  id: '/system/websocket',
  path: '/system/websocket',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRuntimeRoute = SystemRuntimeRouteImport.update({
  id: '/system/runtime',
  path: '/system/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemEdgeRoute = SystemEdgeRouteImport.update({
  id: '/system/edge',
  path: '/system/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemApiHealthRoute = SystemApiHealthRouteImport.update({
  id: '/system/api-health',
  path: '/system/api-health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/correlation': typeof CorrelationRoute
  '/dataset': typeof DatasetRoute
  '/defect-evolution': typeof DefectEvolutionRoute
  '/drift': typeof DriftRoute
  '/features': typeof FeaturesRoute
  '/fft': typeof FftRoute
  '/fusion': typeof FusionRoute
  '/latent': typeof LatentRoute
  '/metrics': typeof MetricsRoute
  '/model-profiles': typeof ModelProfilesRoute
  '/model-validation': typeof ModelValidationRoute
  '/physics': typeof PhysicsRoute
  '/predictive-failure': typeof PredictiveFailureRoute
  '/replay': typeof ReplayRoute
  '/research-export': typeof ResearchExportRoute
  '/spectral': typeof SpectralRoute
  '/standards': typeof StandardsRoute
  '/stations': typeof StationsRoute
  '/stream-control': typeof StreamControlRoute
  '/telemetry': typeof TelemetryRoute
  '/threshold-evolution': typeof ThresholdEvolutionRoute
  '/thresholds': typeof ThresholdsRoute
  '/upload-train': typeof UploadTrainRoute
  '/validation': typeof ValidationRoute
  '/wavelets': typeof WaveletsRoute
  '/xai': typeof XaiRoute
  '/system/api-health': typeof SystemApiHealthRoute
  '/system/edge': typeof SystemEdgeRoute
  '/system/runtime': typeof SystemRuntimeRoute
  '/system/websocket': typeof SystemWebsocketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/correlation': typeof CorrelationRoute
  '/dataset': typeof DatasetRoute
  '/defect-evolution': typeof DefectEvolutionRoute
  '/drift': typeof DriftRoute
  '/features': typeof FeaturesRoute
  '/fft': typeof FftRoute
  '/fusion': typeof FusionRoute
  '/latent': typeof LatentRoute
  '/metrics': typeof MetricsRoute
  '/model-profiles': typeof ModelProfilesRoute
  '/model-validation': typeof ModelValidationRoute
  '/physics': typeof PhysicsRoute
  '/predictive-failure': typeof PredictiveFailureRoute
  '/replay': typeof ReplayRoute
  '/research-export': typeof ResearchExportRoute
  '/spectral': typeof SpectralRoute
  '/standards': typeof StandardsRoute
  '/stations': typeof StationsRoute
  '/stream-control': typeof StreamControlRoute
  '/telemetry': typeof TelemetryRoute
  '/threshold-evolution': typeof ThresholdEvolutionRoute
  '/thresholds': typeof ThresholdsRoute
  '/upload-train': typeof UploadTrainRoute
  '/validation': typeof ValidationRoute
  '/wavelets': typeof WaveletsRoute
  '/xai': typeof XaiRoute
  '/system/api-health': typeof SystemApiHealthRoute
  '/system/edge': typeof SystemEdgeRoute
  '/system/runtime': typeof SystemRuntimeRoute
  '/system/websocket': typeof SystemWebsocketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/correlation': typeof CorrelationRoute
  '/dataset': typeof DatasetRoute
  '/defect-evolution': typeof DefectEvolutionRoute
  '/drift': typeof DriftRoute
  '/features': typeof FeaturesRoute
  '/fft': typeof FftRoute
  '/fusion': typeof FusionRoute
  '/latent': typeof LatentRoute
  '/metrics': typeof MetricsRoute
  '/model-profiles': typeof ModelProfilesRoute
  '/model-validation': typeof ModelValidationRoute
  '/physics': typeof PhysicsRoute
  '/predictive-failure': typeof PredictiveFailureRoute
  '/replay': typeof ReplayRoute
  '/research-export': typeof ResearchExportRoute
  '/spectral': typeof SpectralRoute
  '/standards': typeof StandardsRoute
  '/stations': typeof StationsRoute
  '/stream-control': typeof StreamControlRoute
  '/telemetry': typeof TelemetryRoute
  '/threshold-evolution': typeof ThresholdEvolutionRoute
  '/thresholds': typeof ThresholdsRoute
  '/upload-train': typeof UploadTrainRoute
  '/validation': typeof ValidationRoute
  '/wavelets': typeof WaveletsRoute
  '/xai': typeof XaiRoute
  '/system/api-health': typeof SystemApiHealthRoute
  '/system/edge': typeof SystemEdgeRoute
  '/system/runtime': typeof SystemRuntimeRoute
  '/system/websocket': typeof SystemWebsocketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/correlation'
    | '/dataset'
    | '/defect-evolution'
    | '/drift'
    | '/features'
    | '/fft'
    | '/fusion'
    | '/latent'
    | '/metrics'
    | '/model-profiles'
    | '/model-validation'
    | '/physics'
    | '/predictive-failure'
    | '/replay'
    | '/research-export'
    | '/spectral'
    | '/standards'
    | '/stations'
    | '/stream-control'
    | '/telemetry'
    | '/threshold-evolution'
    | '/thresholds'
    | '/upload-train'
    | '/validation'
    | '/wavelets'
    | '/xai'
    | '/system/api-health'
    | '/system/edge'
    | '/system/runtime'
    | '/system/websocket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/correlation'
    | '/dataset'
    | '/defect-evolution'
    | '/drift'
    | '/features'
    | '/fft'
    | '/fusion'
    | '/latent'
    | '/metrics'
    | '/model-profiles'
    | '/model-validation'
    | '/physics'
    | '/predictive-failure'
    | '/replay'
    | '/research-export'
    | '/spectral'
    | '/standards'
    | '/stations'
    | '/stream-control'
    | '/telemetry'
    | '/threshold-evolution'
    | '/thresholds'
    | '/upload-train'
    | '/validation'
    | '/wavelets'
    | '/xai'
    | '/system/api-health'
    | '/system/edge'
    | '/system/runtime'
    | '/system/websocket'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/correlation'
    | '/dataset'
    | '/defect-evolution'
    | '/drift'
    | '/features'
    | '/fft'
    | '/fusion'
    | '/latent'
    | '/metrics'
    | '/model-profiles'
    | '/model-validation'
    | '/physics'
    | '/predictive-failure'
    | '/replay'
    | '/research-export'
    | '/spectral'
    | '/standards'
    | '/stations'
    | '/stream-control'
    | '/telemetry'
    | '/threshold-evolution'
    | '/thresholds'
    | '/upload-train'
    | '/validation'
    | '/wavelets'
    | '/xai'
    | '/system/api-health'
    | '/system/edge'
    | '/system/runtime'
    | '/system/websocket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnomaliesRoute: typeof AnomaliesRoute
  CorrelationRoute: typeof CorrelationRoute
  DatasetRoute: typeof DatasetRoute
  DefectEvolutionRoute: typeof DefectEvolutionRoute
  DriftRoute: typeof DriftRoute
  FeaturesRoute: typeof FeaturesRoute
  FftRoute: typeof FftRoute
  FusionRoute: typeof FusionRoute
  LatentRoute: typeof LatentRoute
  MetricsRoute: typeof MetricsRoute
  ModelProfilesRoute: typeof ModelProfilesRoute
  ModelValidationRoute: typeof ModelValidationRoute
  PhysicsRoute: typeof PhysicsRoute
  PredictiveFailureRoute: typeof PredictiveFailureRoute
  ReplayRoute: typeof ReplayRoute
  ResearchExportRoute: typeof ResearchExportRoute
  SpectralRoute: typeof SpectralRoute
  StandardsRoute: typeof StandardsRoute
  StationsRoute: typeof StationsRoute
  StreamControlRoute: typeof StreamControlRoute
  TelemetryRoute: typeof TelemetryRoute
  ThresholdEvolutionRoute: typeof ThresholdEvolutionRoute
  ThresholdsRoute: typeof ThresholdsRoute
  UploadTrainRoute: typeof UploadTrainRoute
  ValidationRoute: typeof ValidationRoute
  WaveletsRoute: typeof WaveletsRoute
  XaiRoute: typeof XaiRoute
  SystemApiHealthRoute: typeof SystemApiHealthRoute
  SystemEdgeRoute: typeof SystemEdgeRoute
  SystemRuntimeRoute: typeof SystemRuntimeRoute
  SystemWebsocketRoute: typeof SystemWebsocketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xai': {
      id: '/xai'
      path: '/xai'
      fullPath: '/xai'
      preLoaderRoute: typeof XaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wavelets': {
      id: '/wavelets'
      path: '/wavelets'
      fullPath: '/wavelets'
      preLoaderRoute: typeof WaveletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-train': {
      id: '/upload-train'
      path: '/upload-train'
      fullPath: '/upload-train'
      preLoaderRoute: typeof UploadTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threshold-evolution': {
      id: '/threshold-evolution'
      path: '/threshold-evolution'
      fullPath: '/threshold-evolution'
      preLoaderRoute: typeof ThresholdEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream-control': {
      id: '/stream-control'
      path: '/stream-control'
      fullPath: '/stream-control'
      preLoaderRoute: typeof StreamControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectral': {
      id: '/spectral'
      path: '/spectral'
      fullPath: '/spectral'
      preLoaderRoute: typeof SpectralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-export': {
      id: '/research-export'
      path: '/research-export'
      fullPath: '/research-export'
      preLoaderRoute: typeof ResearchExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive-failure': {
      id: '/predictive-failure'
      path: '/predictive-failure'
      fullPath: '/predictive-failure'
      preLoaderRoute: typeof PredictiveFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics': {
      id: '/physics'
      path: '/physics'
      fullPath: '/physics'
      preLoaderRoute: typeof PhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-validation': {
      id: '/model-validation'
      path: '/model-validation'
      fullPath: '/model-validation'
      preLoaderRoute: typeof ModelValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-profiles': {
      id: '/model-profiles'
      path: '/model-profiles'
      fullPath: '/model-profiles'
      preLoaderRoute: typeof ModelProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latent': {
      id: '/latent'
      path: '/latent'
      fullPath: '/latent'
      preLoaderRoute: typeof LatentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fusion': {
      id: '/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof FusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fft': {
      id: '/fft'
      path: '/fft'
      fullPath: '/fft'
      preLoaderRoute: typeof FftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defect-evolution': {
      id: '/defect-evolution'
      path: '/defect-evolution'
      fullPath: '/defect-evolution'
      preLoaderRoute: typeof DefectEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/websocket': {
      id: '/system/websocket'
      path: '/system/websocket'
      fullPath: '/system/websocket'
      preLoaderRoute: typeof SystemWebsocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/runtime': {
      id: '/system/runtime'
      path: '/system/runtime'
      fullPath: '/system/runtime'
      preLoaderRoute: typeof SystemRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/edge': {
      id: '/system/edge'
      path: '/system/edge'
      fullPath: '/system/edge'
      preLoaderRoute: typeof SystemEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/api-health': {
      id: '/system/api-health'
      path: '/system/api-health'
      fullPath: '/system/api-health'
      preLoaderRoute: typeof SystemApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnomaliesRoute: AnomaliesRoute,
  CorrelationRoute: CorrelationRoute,
  DatasetRoute: DatasetRoute,
  DefectEvolutionRoute: DefectEvolutionRoute,
  DriftRoute: DriftRoute,
  FeaturesRoute: FeaturesRoute,
  FftRoute: FftRoute,
  FusionRoute: FusionRoute,
  LatentRoute: LatentRoute,
  MetricsRoute: MetricsRoute,
  ModelProfilesRoute: ModelProfilesRoute,
  ModelValidationRoute: ModelValidationRoute,
  PhysicsRoute: PhysicsRoute,
  PredictiveFailureRoute: PredictiveFailureRoute,
  ReplayRoute: ReplayRoute,
  ResearchExportRoute: ResearchExportRoute,
  SpectralRoute: SpectralRoute,
  StandardsRoute: StandardsRoute,
  StationsRoute: StationsRoute,
  StreamControlRoute: StreamControlRoute,
  TelemetryRoute: TelemetryRoute,
  ThresholdEvolutionRoute: ThresholdEvolutionRoute,
  ThresholdsRoute: ThresholdsRoute,
  UploadTrainRoute: UploadTrainRoute,
  ValidationRoute: ValidationRoute,
  WaveletsRoute: WaveletsRoute,
  XaiRoute: XaiRoute,
  SystemApiHealthRoute: SystemApiHealthRoute,
  SystemEdgeRoute: SystemEdgeRoute,
  SystemRuntimeRoute: SystemRuntimeRoute,
  SystemWebsocketRoute: SystemWebsocketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
